[package]
name = "ploys"
version = "0.4.0"
description = "A utility to manage projects, packages, releases and deployments."
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
homepage = "https://ploys.dev"
repository = "https://github.com/ploys/ploys"
license = "MIT OR Apache-2.0"
edition = "2024"

[features]
default = ["fs", "git", "github"]
fs = ["dep:walkdir"]
git = ["dep:gix"]
github = ["dep:reqwest"]

[dependencies]
bytes = "1.10.1"
either = "1.13.0"
gix = { version = "0.70.0", optional = true }
globset = "0.4.13"
itertools = "0.14.0"
markdown = "1.0.0"
once_cell = "1.20.2"
semver = "1.0.19"
serde = { version = "1.0.185", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
time = { version = "0.3.36", features = ["serde", "formatting", "parsing"] }
toml_edit = { version = "0.22.14", features = ["serde"] }
tracing = "0.1.41"
url = "2.4.0"
walkdir = { version = "2.5.0", optional = true }

[dependencies.reqwest]
version = "0.12.9"
features = ["blocking", "json"]
optional = true

[dev-dependencies]
indoc = "2.0.5"
pretty_assertions = "1.4.1"
tempfile = "3.15.0"
