[package]
name = "ploys"
version = "0.2.0"
description = "A utility to manage projects, packages, releases and deployments."
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
homepage = "https://ploys.dev"
repository = "https://github.com/ploys/ploys"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = ["git", "github"]
git = ["dep:gix"]
github = ["dep:ureq"]

[dependencies]
gix = { version = "0.66.0", optional = true }
globset = "0.4.13"
markdown = "=1.0.0-alpha.21"
semver = "1.0.19"
serde = { version = "1.0.185", features = ["derive"] }
time = { version = "0.3.36", features = ["serde", "formatting", "parsing"] }
toml_edit = { version = "0.22.14", features = ["serde"] }
ureq = { version = "2.7.1", features = ["json"], optional = true }
url = "2.4.0"

[dev-dependencies]
indoc = "2.0.5"
pretty_assertions = "1.4.1"
