[package]
name = "ploys"
version = "0.0.0"
description = "A utility to manage projects, packages, releases and deployments."
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
homepage = "https://ploys.dev"
repository = "https://github.com/ploys/ploys"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
gix = "0.66.0"
globset = "0.4.13"
semver = "1.0.19"
serde = { version = "1.0.185", features = ["derive"] }
toml_edit = { version = "0.22.14", features = ["serde"] }
ureq = { version = "2.7.1", features = ["json"] }
url = "2.4.0"

[dependencies.git2]
version = "0.19.0"
features = ["vendored-libgit2", "vendored-openssl"]
