[package]
name = "ploys"
version = "0.0.0"
description = "A utility to manage projects, packages, releases and deployments."
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
homepage = "https://ploys.dev"
repository = "https://github.com/ploys/ploys"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
cargo_toml = "0.16.2"
gix = "0.51.0"
globset = "0.4.13"
serde = { version = "1.0.185", features = ["derive"] }
ureq = { version = "2.7.1", features = ["json"] }
url = "2.4.0"
