[package]
name = "ploys-cli"
version = "0.3.0"
description = "A command line application to manage projects, packages, releases and deployments."
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
homepage = "https://ploys.dev"
repository = "https://github.com/ploys/ploys"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive", "env"] }
console = "0.15.7"
dialoguer = "0.11.0"
itertools = "0.14.0"
ploys = { version = "0.4.0", path = "../ploys" }
strum = { version = "0.26.3", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.4.0"

[dependencies.clap-verbosity-flag]
version = "3.0.2"
features = ["tracing"]
default-features = false

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = { version = "3.0.3", features = ["regex"] }
tempfile = "3.15.0"

[[bin]]
name = "ploys"
path = "src/main.rs"
