[package]
name = "ploys-cli"
version = "0.0.0"
description = "A command line application to manage projects, packages, releases and deployments."
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
homepage = "https://ploys.dev"
repository = "https://github.com/ploys/ploys"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive"] }
console = "0.15.7"
gix = "0.51.0"

[[bin]]
name = "ploys"
path = "src/main.rs"
