name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            toolchain: stable
            os: macos-latest

          - target: x86_64-apple-darwin
            toolchain: stable
            os: macos-latest

          - target: x86_64-pc-windows-msvc
            toolchain: stable
            os: windows-latest

          - target: x86_64-unknown-linux-gnu
            toolchain: stable
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: dtolnay/rust-toolchain@master
        with:
          targets: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --target ${{ matrix.target }} -- --include-ignored
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: dtolnay/rust-toolchain@master
        with:
          targets: x86_64-unknown-linux-gnu
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings
